{
	"cmd": ["make"],
	"working_dir": "${file_path}",
	"shell" : false,

	"variants":
	[
		{
			"name": "All",
			"working_dir": "${file_path}",
			"cmd": ["make", "all"]
		},
		{
			"name": "Clean",
			"working_dir": "${file_path}",
			"cmd": ["make", "clean"]
		},
		{
			"name": "Run",
			"working_dir": "${file_path}",
			"cmd": ["make", "run"]
		}
	]
}
